# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
## 使用starter log4j2省略log4j2.xml文件
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Spring settings
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: netty-gateway
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAPSERVERS:10.0.11.36:9092,10.0.11.37:9092,10.0.11.38:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID_PVO:netty-gateway}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 50
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      tbox: zs-tbox
  redis:
    password: ${REDIS_PASSWORD:redis2019}
    database: ${REDIS_DATABASE:1}
    host: ${REDIS_HOST:10.0.11.23}
    port: ${REDIS_PORT:6379}
    #cluster:
    #  max-redirects: ${REDIS_CLUSTER_MAX_REDIRECTS:6}
    #  nodes: ${REDIS_CLUSTER_NODES}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

# Incarcloud settings
incarcloud:
  host:
    # 配置slot解析器，协议与服务端口
    slots:
      #- DataParserIc:tcp:6666
      - DataParserJtt808:tcp:10666
  gateway:
    # 网关服务端口
    server:
      port: ${GATEWAY_SERVER_PORT:40020}
