# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}

# Management settings
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    elasticsearch:
      enabled: false

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      sample: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:500MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:7}
    total-size-cap: ${LOGGING_FILE_TOTAL_SIZE:1500MB}
  pattern:
    rolling-file-name: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: netty-server-blank

# Netty settings
netty:
  serverPort: 7777
